title: Exploring Software Developers' Home Workstations
email: fronchettl@vcu.edu
description: This is a replication package provided by VCU Software Engineering.
github_username: fronchetti
baseurl: /workstations
repository: https://github.com/vcuse/workstations

collections:
  stages:
    output: true
    permalink: /:collection/:name
    order:
      - overview.md
      - stage-one.md
      - stage-two.md
      - stage-three.md
  tutorial:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-toc
