# About
title: Workstations
email: fronchettl@vcu.edu
description: "Understanding what is important to have on a developer workstation."
baseurl: "/reddit"
url: "https://fronchetti.org"
github_username:  fronchetti

plugins:
  - jekyll-last-modified-at
