# About
title: Workstations
email: fronchettl@vcu.edu
description: "Understanding what is important to have on a developer workstation."
baseurl: "/workstations"
url: "https://fronchetti.org"
github_username:  fronchetti
